// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prqgrvpzrubgyyzvndda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBycWdydnB6cnViZ3l5enZuZGRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNzQ2NzAsImV4cCI6MjA1ODk1MDY3MH0.9-T8snazVVfjJkADKnBvBJgYwStE7uB6ZIF8_9SQnQs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);